name: generate PageSpeed Insights report
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  create-psi-report-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: pip setting
        run: |
          python -m pip install --upgrade pip
          pip install datetime
          pip install requests
          pip install json
      - name: run python
        working-directory: src/scripts
        run: |
          python pageSpeedInsight.py　
          mv *.json ./../../public/data/psi/
      - name: commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'generate PageSpeed Insights report of today'
          git push origin main　　# mainブランチにプッシュ
